MENU = '\n1. Mostrar las reservas del dia\n2. Exportar los datos BBDD a CSV\n3. Mostrar datos del fichero CSV\n4. Mostrar Beneficios del dia\n5. Registrar nuevo cliente\n6. Registrar nueva reserva\n0. Salir\n'
NIF = 'Introduce el NIF del cliente: '
NOM = 'Introduce el nombre del cliente: '
COGNOM1 = 'Introduce el primer apellido del cliente: '
COGNOM2 = 'Introduce el segundo apellido del cliente: '
ADDRESS = 'Introduce la direccion del cliente: '
PROVINCE = 'Introduce la provincia del cliente: '
POBLACION = 'Introduce la poblacion del cliente: '
TELEFON = 'Introduce el telefono del cliente: '
EMAIL = 'Introduce el email del cliente: '
DATANAIXEMENT = 'Introduce la fecha de nacimiento del cliente: '
MOTIVO = 'Introduce el motivo de la reserva: '
SERVICIO = 'Introduce el servicio de la reserva: '

