MENU = '\n1. Introducir videos\n2. Select\n0. Salir\n'
ID = 'Introduce el numerador(numerico): '
SINGER = 'Introduce el grupo/cantante: '
SONG = 'Introduce el nombre de la cancion: '
DATE = 'Introduce la fecha de publicacion(YYYY-MM--DD): '
DAY = 'Introduce el dia: '
MES = 'Introduce el mes: '
ANNO = 'Introduce el año: '
VISUAL = 'Introduce el numero de visualizaciones: '

